"use client";

import { useEffect, useMemo, useState } from "react";
import type { FormEvent, ReactNode } from "react";

type Page = "home" | "announcements" | "jobs" | "phones";
type Post = { id: number; kind: "Duyuru" | "Etkinlik"; title: string; date: string; text: string; image?: string };
type Job = { id: number; title: string; company: string; location: string; type: string; deadline: string; image?: string; details?: string; phone?: string };

const initialPosts: Post[] = [
  { id: 1, kind: "Etkinlik", title: "Park ve yeşil alanlarda ilaçlama çalışması", date: "Altay Mahallesi", text: "Mahallemizdeki park ve yeşil alanlarda çevre sağlığını korumaya yönelik ilaçlama çalışması gerçekleştirildi.", image: "/images/park-ilaclama.png" },
  { id: 2, kind: "Etkinlik", title: "Muhtarlık başvuru ve evrak çalışmaları", date: "Altay Mahallesi", text: "Mahalle sakinlerimizin başvuru ve taleplerine ilişkin evrak çalışmaları muhtarlığımızda sürdürüldü.", image: "/images/muhtarlik-calismasi.png" },
  { id: 3, kind: "Duyuru", title: "Muhtarlığımızın çalışma saatleri", date: "Güncel", text: "Hafta içi her gün 09.00–17.00 saatleri arasında hizmet veriyoruz. İletişim bilgilerimizden bize ulaşabilirsiniz." },
];
const initialJobs: Job[] = [
  { id: 1, title: "Online Sipariş Hazırlama Personeli", company: "Marketten Eryaman (Dark Store)", location: "Göksu Mah. 84. Sk. Meydan Eryaman Sitesi No:1/4H Etimesgut/Ankara", type: "2 vardiya", deadline: "Başvurular telefonla", image: "/images/marketten-is-ilani.png", details: "18 yaş üzeri, en az lise mezunu bay-bayan personel aranmaktadır. Çalışma saatleri 09.00–18.00 ve 14.30–23.30; SGK + asgari ücret + prim.", phone: "0312 375 29 00 / Dahili: 122" },
];
const slides = [
  { image: "/images/serap-demirkiran.png", title: "Serap Demirkıran", text: "Altay Mahallesi Muhtarı" },
  { image: "/images/park-ilaclama.png", title: "Park ve yeşil alan çalışmaları", text: "Altay Mahallesi" },
  { image: "/images/muhtarlik-calismasi.png", title: "Muhtarlık çalışmaları", text: "Başvuru ve evrak işlemleri" },
  { image: "/images/muhtarlik-ziyareti.png", title: "Muhtarlık ziyaretleri", text: "Mahalle sakinlerimizle görüşmeler" },
];
const phones = [["112", "Acil Çağrı Merkezi", "112"], ["01", "Belediye", "0212 555 01 01"], ["02", "Zabıta", "153"], ["03", "Aile Sağlığı Merkezi", "0212 555 02 02"], ["04", "Nöbetçi Eczaneler", "Ankara / Etimesgut"], ["05", "Doğalgaz Arıza", "187"]];

export default function Home() {
  const [page, setPage] = useState<Page>("home");
  const [posts, setPosts] = useState(initialPosts);
  const [jobs, setJobs] = useState(initialJobs);
  const [adminOpen, setAdminOpen] = useState(false);
  const [logged, setLogged] = useState(false);
  const [otpStep, setOtpStep] = useState(false);
  const [toast, setToast] = useState("");
  const [slideIndex, setSlideIndex] = useState(0);
  const [postFilter, setPostFilter] = useState<"Tümü" | "Duyuru" | "Etkinlik">("Tümü");
  const visiblePosts = useMemo(() => postFilter === "Tümü" ? posts : posts.filter(p => p.kind === postFilter), [posts, postFilter]);
  const go = (next: Page) => { setPage(next); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 3500); };
  useEffect(() => {
    const timer = window.setInterval(() => setSlideIndex((current) => (current + 1) % slides.length), 5000);
    return () => window.clearInterval(timer);
  }, []);

  function contactSubmit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); notify("Mesajınız alındı. En kısa sürede size dönüş yapacağız."); e.currentTarget.reset(); }
  function whatsappSubmit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); notify("Katılım talebiniz muhtarımıza iletildi. Teşekkür ederiz!"); e.currentTarget.reset(); }

  return <main>
    <header className="site-header"><div className="topline"><div className="container topinner"><span>Altay Mahallesi Muhtarlığı</span><span>Muhtarlık: Hafta içi 09.00–17.00</span></div></div>
      <div className="container nav"><button className="brand" onClick={() => go("home")}><span className="brandmark">A</span><span><b>Altay</b><small>Mahallesi Muhtarlığı</small></span></button><nav>{([["home", "Anasayfa"], ["announcements", "Duyuru & Etkinlikler"], ["jobs", "İş İlanları"], ["phones", "Önemli Telefonlar"]] as [Page,string][]).map(([id,label]) => <button key={id} className={page === id ? "active" : ""} onClick={() => go(id)}>{label}</button>)}</nav><button className="admin-link" onClick={() => setAdminOpen(true)}>Yönetici girişi <span>↗</span></button></div>
    </header>

    {page === "home" && <>
      <section className="hero"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow">ALTAY MAHALLESİ MUHTARLIĞI</div><h1>Altay Mahallesi<br /><em>Muhtarlığı</em></h1><p>Mahallemizdeki duyurulara, etkinliklere, iş ilanlarına ve önemli telefonlara tek bir yerden ulaşın.</p><div className="hero-actions"><button className="button primary" onClick={() => go("announcements")}>Duyuruları keşfet <span>→</span></button><button className="text-button" onClick={() => document.getElementById("about")?.scrollIntoView({ behavior: "smooth" })}>Muhtarlığımız hakkında <span>↓</span></button></div></div><div className="hero-photo slideshow" aria-roledescription="slayt gösterisi"><img key={slides[slideIndex].image} src={slides[slideIndex].image} alt={slides[slideIndex].title} /><div className="photo-tag"><span className="tag-dot" /><b>{slides[slideIndex].title}</b><small>{slides[slideIndex].text}</small></div><button className="slide-arrow prev" aria-label="Önceki fotoğraf" onClick={() => setSlideIndex((slideIndex - 1 + slides.length) % slides.length)}>‹</button><button className="slide-arrow next" aria-label="Sonraki fotoğraf" onClick={() => setSlideIndex((slideIndex + 1) % slides.length)}>›</button><div className="slide-dots">{slides.map((slide, index) => <button key={slide.image} className={index === slideIndex ? "current" : ""} aria-label={`${index + 1}. fotoğrafı göster`} onClick={() => setSlideIndex(index)} />)}</div></div></div></section>
      <section className="quick-links"><div className="container quick-grid"><button onClick={() => go("announcements")}><span className="quick-icon amber">✦</span><span><b>Son duyurular</b><small>Mahallemizden haberler</small></span><i>→</i></button><button onClick={() => go("jobs")}><span className="quick-icon green">⌁</span><span><b>İş ilanları</b><small>Yeni fırsatları keşfedin</small></span><i>→</i></button><button onClick={() => go("phones")}><span className="quick-icon blue">◉</span><span><b>Önemli telefonlar</b><small>İhtiyacınız olduğunda</small></span><i>→</i></button></div></section>
      <section id="about" className="section about"><div className="container about-grid"><div><div className="eyebrow">MUHTARINIZ</div><h2>Muhtarlık<br /><em>bilgileri</em></h2><p className="lead">Altay Mahallesi Muhtarlığı olarak mahalle sakinlerinin talepleri, başvuruları ve ihtiyaçları için hizmet veriyoruz.</p><button className="text-button" onClick={() => notify("Muhtarlığımıza bekleriz!")}>Bize uğrayın <span>→</span></button></div><div className="muhtar-card"><img src="/images/serap-demirkiran.png" alt="Altay Mahallesi Muhtarı Serap Demirkıran" /><div><span className="eyebrow">ALTAY MAHALLESİ MUHTARI</span><h3>Serap Demirkıran</h3><p>31 Mart 2019 yerel seçimlerinde göreve seçilmiş olup muhtarlık görevini sürdürmektedir.</p></div></div></div></section>
      <section className="section activities"><div className="container"><div className="section-head"><div><div className="eyebrow">MUHTARLIK HAKKINDA</div><h2>Bilinen çalışmaları ve faaliyetleri</h2></div></div><div className="activity-grid"><article><span>01</span><h3>Muhtarlık görevi</h3><p>İlk olarak 31 Mart 2019 yerel seçimlerinde Altay Mahallesi muhtarı seçilmiş ve görevine günümüzde de devam etmektedir.</p></article><article><span>02</span><h3>Mahalle yönetimi</h3><p>Sosyal medya hesapları üzerinden mahallenin altyapı sorunları, yerel esnafa destek projeleri ve resmî kurumlarla koordinasyon süreçlerine dair düzenli paylaşımlar yapmaktadır.</p></article><article><span>03</span><h3>Kadın kooperatifleri</h3><p>Bölgedeki kadın girişimciliğini desteklemek amacıyla yürütülen Eryaman Öncü Kadınlar Kooperatifi gibi kermes ve yerel kadın dayanışma etkinliklerinde aktif rol almaktadır.</p></article></div></div></section>
      <section className="section soft"><div className="container"><div className="section-head"><div><div className="eyebrow">GÜNCEL</div><h2>Mahallemizde neler oluyor?</h2></div><button className="outline-button" onClick={() => go("announcements")}>Tümünü gör →</button></div><div className="post-grid">{posts.slice(0, 3).map(post => <PostCard key={post.id} post={post} />)}</div></div></section>
      <section className="section gallery"><div className="container"><div className="section-head"><div><div className="eyebrow">ALTAY MAHALLESİ</div><h2>Mahalle etkinlikleri<br /><em>ve çalışmalar</em></h2></div><p>Altay Mahallesi'ndeki etkinliklerden ve çalışmalardan fotoğraflar.</p></div><div className="gallery-grid"><img src="/images/park-ilaclama.png" alt="Park ve yeşil alanlarda ilaçlama çalışması" /><img src="/images/muhtarlik-calismasi.png" alt="Muhtarlık başvuru ve evrak çalışmaları" /><img src="/images/muhtarlik-ziyareti.png" alt="Muhtarlık ziyareti" /></div></div></section>
    </>}

    {page === "announcements" && <ListingPage title="Duyuru & Etkinlikler" eyebrow="ALTAY MAHALLESİNDEN HABERLER" intro="Altay Mahallesi'ndeki duyuruları ve etkinlikleri buradan takip edin." actions={<div className="filters">{["Tümü", "Duyuru", "Etkinlik"].map(f => <button key={f} className={postFilter === f ? "selected" : ""} onClick={() => setPostFilter(f as typeof postFilter)}>{f}</button>)}</div>}><div className="post-grid full">{visiblePosts.map(p => <PostCard key={p.id} post={p} />)}</div></ListingPage>}
    {page === "jobs" && <ListingPage title="İş İlanları" eyebrow="ALTAY MAHALLESİNDE FIRSATLAR" intro="Altay ve çevresindeki güncel iş fırsatlarına göz atın. İlanlar muhtarlığımız tarafından paylaşılmaktadır."><div className="jobs-list">{jobs.map(job => <article className={`job-card ${job.image ? "featured-job" : ""}`} key={job.id}>{job.image ? <img className="job-poster" src={job.image} alt={`${job.company} iş ilanı`} /> : <div className="company-logo">{job.company.slice(0,1)}</div>}<div className="job-main"><span className="job-type">{job.type}</span><h3>{job.title}</h3><p className="job-company">{job.company}</p>{job.details && <p className="job-details">{job.details}</p>}<p>{job.location}</p>{job.phone && <a className="job-phone" href="tel:03123752900">İletişim: {job.phone}</a>}</div><div className="deadline">Başvuru bilgisi<br /><b>{job.deadline}</b></div></article>)}</div></ListingPage>}
    {page === "phones" && <ListingPage title="Önemli Telefonlar" eyebrow="İHTİYACINIZ OLDUĞUNDA" intro="Acil durumlarda ve günlük ihtiyaçlarınızda işinize yarayacak telefon numaraları."><div className="phone-grid">{phones.map(([n, name, phone]) => { const pharmacy = name === "Nöbetçi Eczaneler"; return <a className="phone-card" href={pharmacy ? "https://www.eczaneler.gen.tr/nobetci-ankara-etimesgut" : `tel:${phone.replaceAll(" ", "")}`} target={pharmacy ? "_blank" : undefined} rel={pharmacy ? "noreferrer" : undefined} key={name}><span className="phone-number">{n}</span><span><b>{name}</b><strong>{pharmacy ? "Etimesgut listesini göster" : phone}</strong></span><i>↗</i></a>; })}</div></ListingPage>}

    <section className="contact-section"><div className="container contact-grid"><div><div className="eyebrow">BİZE ULAŞIN</div><h2>İletişim<br /><em>bilgileri</em></h2><p>Önerilerinizi, dileklerinizi ve şikayetlerinizi bizimle paylaşın.</p><div className="contact-details"><span>✉</span> <a href="mailto:muhtarlik@altay.org">muhtarlik@altay.org</a><span>⌕</span> <a href="tel:+902125550101">0212 555 01 01</a></div></div><form className="message-form" onSubmit={contactSubmit}><div className="form-row"><label>Gönderen e-posta<input name="from" required type="email" placeholder="siz@mail.com" /></label><label>Gönderilen e-posta<input value="muhtarlik@altay.org" readOnly /></label></div><label>Mail başlığı<input name="subject" required placeholder="Mesajınızın konusu" /></label><label>Mail içeriği<textarea name="message" required placeholder="Mesajınızı buraya yazın..." /></label><button className="button primary" type="submit">Mesajı gönder <span>→</span></button></form></div></section>
    <section className="whatsapp"><div className="container whatsapp-inner"><div><span className="whatsapp-icon">◔</span><div><div className="eyebrow">MAHALLE DAYANIŞMASI</div><h3>WhatsApp grubumuza katılın</h3><p>Mahallemizdeki gelişmelerden anında haberdar olun.</p></div></div><form onSubmit={whatsappSubmit}><input required type="tel" placeholder="05xx xxx xx xx" aria-label="Telefon numaranız" /><button type="submit">Katılma talebi gönder →</button></form></div></section>
    <footer><div className="container footer-grid"><button className="brand" onClick={() => go("home")}><span className="brandmark">A</span><span><b>Altay</b><small>Mahallesi Muhtarlığı</small></span></button><p>Altay Mahallesi Muhtarlığı</p><div className="social">Instagram ↗ &nbsp; <a href="mailto:muhtarlik@altay.org">E-posta ↗</a></div></div></footer>
    {toast && <div className="toast">✓ {toast}</div>}
    {adminOpen && <AdminModal logged={logged} setLogged={setLogged} otpStep={otpStep} setOtpStep={setOtpStep} close={() => setAdminOpen(false)} addPost={(p) => setPosts([p, ...posts])} addJob={(j) => setJobs([j, ...jobs])} notify={notify} />}
  </main>;
}

function PostCard({ post }: { post: Post }) { return <article className="post-card">{post.image ? <img src={post.image} alt="" /> : <div className="post-placeholder"><span>✦</span></div>}<div className="post-body"><div className="post-meta"><span className={post.kind === "Etkinlik" ? "pill green-pill" : "pill"}>{post.kind}</span><small>{post.date}</small></div><h3>{post.title}</h3><p>{post.text}</p><button className="text-button">Devamını oku →</button></div></article>; }
function ListingPage({ title, eyebrow, intro, actions, children }: { title: string; eyebrow: string; intro: string; actions?: ReactNode; children: ReactNode }) { return <section className="listing"><div className="container"><div className="listing-head"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{intro}</p></div>{actions}</div>{children}</div></section>; }

function AdminModal({ logged, setLogged, otpStep, setOtpStep, close, addPost, addJob, notify }: { logged: boolean; setLogged: (v:boolean)=>void; otpStep: boolean; setOtpStep:(v:boolean)=>void; close:()=>void; addPost:(p:Post)=>void; addJob:(j:Job)=>void; notify:(s:string)=>void }) {
  const [tab, setTab] = useState<"post"|"job">("post");
  const login = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); setOtpStep(true); };
  const verify = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); setLogged(true); setOtpStep(false); };
  const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); if(tab === "post") addPost({ id: Date.now(), kind: f.get("kind") as Post["kind"], title: String(f.get("title")), date: String(f.get("date")), text: String(f.get("text")), image: String(f.get("image") || "") }); else addJob({ id: Date.now(), title: String(f.get("title")), company: String(f.get("company")), location: String(f.get("location")), type: String(f.get("type")), deadline: String(f.get("deadline")) }); notify("İçerik başarıyla yayınlandı."); e.currentTarget.reset(); };
  return <div className="modal-backdrop"><div className="modal"><button className="close" onClick={close}>×</button>{!logged ? (!otpStep ? <><div className="modal-icon">⌘</div><div className="eyebrow">GÜVENLİ YÖNETİCİ PANELİ</div><h2>Hoş geldiniz.</h2><p className="modal-intro">Mahalle içeriklerini yönetmek için giriş yapın.</p><form className="admin-form" onSubmit={login}><label>E-posta adresi<input required type="email" placeholder="admin@altay.org" /></label><label>Şifre<input required type="password" placeholder="••••••••" /></label><button className="button primary" type="submit">Devam et →</button></form></> : <><div className="modal-icon">✉</div><div className="eyebrow">E-POSTA DOĞRULAMA</div><h2>Kodunuzu girin.</h2><p className="modal-intro">admin@altay.org adresine gönderilen 6 haneli kodu girin.</p><form className="admin-form" onSubmit={verify}><input className="otp" inputMode="numeric" maxLength={6} required placeholder="000 000" aria-label="Doğrulama kodu" /><button className="button primary" type="submit">Doğrula ve giriş yap →</button></form></>) : <><div className="admin-top"><div><div className="eyebrow">YÖNETİCİ PANELİ</div><h2>İçerik ekle</h2></div><span className="status">● Yayında</span></div><div className="admin-tabs"><button className={tab === "post" ? "selected" : ""} onClick={() => setTab("post")}>Duyuru / Etkinlik</button><button className={tab === "job" ? "selected" : ""} onClick={() => setTab("job")}>İş ilanı</button></div><form className="admin-form" onSubmit={submit}><label>{tab === "post" ? "İçerik türü" : "İlan başlığı"}{tab === "post" ? <select name="kind"><option>Duyuru</option><option>Etkinlik</option></select> : <input required name="title" placeholder="Örn. Kasiyer aranıyor" />}</label>{tab === "post" ? <><label>Başlık<input required name="title" placeholder="İçerik başlığı" /></label><label>Tarih<input required name="date" placeholder="24 Ağustos 2026" /></label><label>Metin<textarea name="text" required placeholder="İçeriğinizi yazın..." /></label><label>Fotoğraf bağlantısı <span className="optional">(opsiyonel)</span><input name="image" type="url" placeholder="https://..." /></label></> : <><label>Firma / İşveren<input required name="company" placeholder="Firma adı" /></label><label>Konum<input required name="location" placeholder="Mahalle / ilçe" /></label><label>Çalışma şekli<select name="type"><option>Tam zamanlı</option><option>Yarı zamanlı</option><option>Günlük</option></select></label><label>Son başvuru tarihi<input required name="deadline" placeholder="30 Ağustos 2026" /></label></>}<button className="button primary" type="submit">Yayınla <span>→</span></button></form></>}</div></div>;
}
